services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - backend
    networks:
      - "front-back-network"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./conf/nginx.conf.template:/etc/nginx/nginx.conf.template
    env_file:
      - .env
    command: /bin/sh -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    
  backend:
    build:
      dockerfile: ./backend/Dockerfile
    container_name: backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    networks:
      - front-back-network
      - backside-network
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:${PORT}/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20



  database:
    image: postgres:15
    restart: unless-stopped
    container_name: postgres_db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - backside-network
    volumes:
      - info_storage:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  info_storage:

networks:
  front-back-network:
    driver: bridge
  backside-network:
    driver: bridge